name: Build and Deploy with Gulp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.0'

      - name: Install dependencies
        run: npm install
      
      - name: List installed packages
        run: npm list --depth=0

      - name: Run Gulp build
        env:
            NODE_ENV: production # Add any other necessary variables
        run: npm run build
      
      - name: Commit dist files
        env:
          GITHUB_TOKEN: ${{ secrets.MITRA_TOKEN }} # Use your secret here
        run: |
          git config --local user.email "mitrakashmiri@gmail.com"
          git config --local user.name "Mitra Kashmiri"
          git add dist
          git commit -m "Update dist directory" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/PHPallas/UI.git HEAD:main
