name: Build and Deploy with Gulp

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Gulp build
        run: npm run build  # Assumes you have a build script in package.json

      - name: Upload dist folder
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
